<!DOCTYPE html>
<html>
<head>
    <title>Student Webstore</title>
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="style.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.0.1-p7/css/bootstrap.min.css">
</head>
<body>
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.0.1-p7/js/bootstrap.min.js"></script>
<nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <a class="navbar-brand" href="/?p=1">My Product Catalog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
            <?php if(!$this->session()->isUserNameSet()): ?>
                <li><a href="?page=customer_login">Login</a></li>
                <li><a href="?page=customer_register">Register</a></li>
            <?php endif; if($this->session()->isUserNameSet()):?>
                <li><p class="navbar-text">Logged in as <?php echo $this->session()->getUserName(); ?></p></li>
            <?php endif; if(!$this->session()->isAdmin()): ?>
                <li><a href="?page=customer_exit">Exit</a></li>
                <li><a href="?page=quote_list">Cart</a></li>
            <?php endif; if($this->session()->isAdmin()): ?>
                <li><a href="?page=admin_exit">Exit</a></li>
            <?php endif; ?>
        </ul>
    </div><!-- /.navbar-collapse -->
</nav>
<?php
    if(!$this->session()->isAdmin()) $this->renderTemplate();
    else $this->renderMenu();
?>
</body>
</html>