<!DOCTYPE html>
<html>
<head>
    <title>Student Webstore</title>
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
    <div class="login">
        <?php if(!\App\Model\Session::isUserNameSet()): ?>
            <a href="?page=customer_login">Login</a> |
            <a href="?page=customer_register">Register</a> |
            <a href="?page=basket_view"> Basket</a>
        <?php endif; if(\App\Model\Session::isUserNameSet()):?>
            Logged in as <?php echo \App\Model\Session::getUserName(); ?>
            <a href="?page=customer_exit"> Exit</a> |
            <a href="?page=basket_view"> Basket</a>
        <?php endif; ?>
    </div>
    <div class="list">
        <?php require_once __DIR__ . "/../{$view}.phtml"; ?>
    </div>
</body>
</html>