<div class="container">
    <div class="jumbotron text-center">
            <h2>Admin Entrance</h2>
            <form action = "/?page=admin_login&&magic_word=please" method="post" class="navbar-form text-center">
                <div class="form-group">
                    <input type="text" id="name" name="admin[name]" class="form-control" placeholder="Name">
                    <input type="password" id="password" name="admin[password]" class="form-control" placeholder="Password">
                    <input type="submit" value="Enter" class="btn btn-default">
                </div>
            </form>
    </div>
</div>