<div class="container">
    <div class="jumbotron">
        <h3><a href="/?page=checkout_address">&larrhk;</a>
        Shipping step:</h3>
        <form action = "/?page=checkout_shipping" method="post" class="navbar-form">
            <div class="form-group">
                <select class="form-control" id="shipping" name="shipping">
                    <?php foreach($this->get('methods') as $method): ?>
                        <option value=<?php echo $method->getCode(); ?>
                            <?php if($this->get('shipping_code') == $method->getCode()): ?>
                                selected
                            <?php endif; ?>
                            >
                            <?php echo $method->getLabel() . $method->getPrice(); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <input type="submit" value="Next" class="btn btn-default">
            </div>
        </form>
    </div>
</div>