<div class="container">
    <div class="jumbotron text-center">
        <h2>Checkout</h2>
        <form action = "/?page=checkout_address" method="post" class="navbar-form text-center">
            <div class="form-group">
                <input type="text" id="region" name="address[region]" class="form-control" placeholder="Region">
                <input type="text" id="city" name="address[city]" class="form-control" placeholder="City">
                <input type="submit" value="Next" class="btn btn-default">
            </div>
        </form>
    </div>
</div>