<div class="container">
    <div class="jumbotron text-center">
        <h2>Checkout: choose shipping method</h2>
        <form action = "/?page=checkout_shipping" method="post" class="navbar-form text-center">
            <div class="form-group">
                <select name="code">
                    <option>fixed</option>
                    <option>table_rate</option>
                </select>
                <input type="submit" value="Next" class="btn btn-default">
            </div>
        </form>
    </div>
</div>