<div class="container">
    <div class="jumbotron">
        <h3><a href="/?page=checkout_shipping">&larrhk;</a>
            Payment step:</h3>
        <form action = "/?page=checkout_payment" method="post" class="navbar-form">
            <div class="form-group">
                <select class="form-control" id="payment" name="payment">
                    <?php foreach($this->get('methods') as $method): ?>
                        <option value=<?php echo $method->getCode(); ?>
                                <?php if($this->get('payment_code') == $method->getCode()): ?>
                                selected
                            <?php endif; ?>
                            >
                            <?php echo $method->getLabel(); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <input type="submit" value="Next" class="btn btn-default">
            </div>
        </form>
    </div>
</div>