<div class="container">
    <div class="jumbotron">
        <?php if(!$this->get('result')): ?>
        <h2 class="text-center">Join us!</h2>
        <form action = "/?page=customer_register" method="post" class="navbar-form text-center">
            <div class="form-group">
                <input type="text" id="name" name="customer[name]" class="form-control" placeholder="Name">
                <input type="password" id="password" name="customer[password]" class="form-control" placeholder="Password">
                <input type="submit" value="Register" class="btn btn-default">
            </div>
        </form>
        <?php endif; if($this->get('result')):?>
            <p class="text-center">
                Congratulations! Return to <a href="/">product list</a>?
            </p>
        <?php endif; ?>
    </div>
</div>