<?php
$id = 0;
if(isset($_POST['sh_id'])) $id = $_POST['sh_id'];
?>
<script>
    function setId(id,purpose)
    {
        var f = document.getElementById('edit');
        if(purpose == 'edit')
        {
            f.delete_id.disabled = true;
            f.sh_id.value = id;
        }
        if(purpose == 'delete')
        {
            f.delete_id.value = id;
        }
        f.submit();
    }
</script>
<form method="post" action="/?page=manage_shipping" class="form-inline">
    <div class="form-group">
        <input type="text" name="search_request" class="form-control" style="width: 200px" placeholder="...">
        <input type="submit" class="btn btn-default" value="find">
    </div>
</form>
<form method="post" id="edit" action="/?page=manage_shipping">
    <table class="table">
        <tr>
            <td>City
                <!-- THIS FORM TAG DISAPPEARS MAGICALLY!!! -->
                <form method="post" id="first" action="/?page=manage_shipping" class="inline">
                    <!--<input type="hidden" name="sort[sort_field]" value="city"/>
                    <input type="hidden" name="sort[sort_direction]" value="asc"/>-->
                    <input type="submit" value="&DownArrow;" class="link-like"/>
                </form>
                <!-- THIS FORM TAG DISAPPEARS MAGICALLY!!! -->
                <form method="post" action="/?page=manage_shipping" class="inline"/>
                    <input type="hidden" name="sort[sort_field]" value="city"/>
                    <input type="hidden" name="sort[sort_direction]" value="desc"/>
                    <input type="submit" value="&uparrow;" class="link-like"/>
                </form>
            </td>
            <td>Price
                <form method="post" action="/?page=manage_shipping" class="inline">
                    <input type="hidden" name="sort[sort_field]" value="price">
                    <input type="hidden" name="sort[sort_direction]" value="asc">
                    <input type="submit" value="&DownArrow;" class="link-like">
                </form>
                <form method="post" action="/?page=manage_shipping" class="inline">
                    <input type="hidden" name="sort[sort_field]" value="price">
                    <input type="hidden" name="sort[sort_direction]" value="desc">
                    <input type="submit" value="&uparrow;" class="link-like">
                </form>
            </td>
            <td></td>
        </tr>
        <?php foreach($this->get('collection') as $item): ?>
            <tr>
                <?php if($id == $item->getId()): ?>
                    <td>
                        <select id="city" name="shipping[city]" class="form-control">
                            <?php foreach($this->get('cities') as $city): ?>
                                <option
                                    <?php if($city->getCity() == $item->getCity()): ?>
                                        selected
                                    <?php endif; ?>
                                    >
                                    <?php echo $city->getCity(); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <td><input type="text" value="<?php echo $item->getPrice(); ?>" class="form-control" name="shipping[price]" placeholder="Price"></td>
                    <td><input type="submit" value="save" class="btn btn-default"></td>
                <?php endif; if($id != $item->getId()): ?>
                    <td>
                        <?php echo $item->getCity(); ?>
                    </td>
                    <td>
                        <?php echo $item->getPrice(); ?>
                    </td>
                    <td>
                        <input type="button" value="edit" class="btn btn-default" onclick="setId(<?php echo $item->getId(); ?>,'edit')">
                        <input type="button" value="delete" class="btn btn-default" onclick="setId(<?php echo $item->getId(); ?>,'delete')">
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </table>
    <input type="hidden" name="sh_id" value="">
    <input type="hidden" name="delete_id" value="">
</form>
<?php if(isset($_POST['add'])): ?>
    <form method="post" action="/?page=manage_shipping">
        <table class="table">
            <tr>
                <td>
                    <select id="city" name="shipping[city]" class="form-control">
                        <?php foreach($this->get('cities') as $city): ?>
                            <option>
                                <?php echo $city->getCity(); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td><input type="text" class="form-control" name="shipping[price]" placeholder="Price"></td>
                <td><input type="submit" value="add" class="btn btn-default"></td>
            </tr>
        </table>
    </form>
<?php endif; if(!isset($_POST['add'])): ?>
<form method="post" action="/?page=manage_shipping">
    <input type="hidden" value="true" name="add">
    <input type="submit" value="add" class="btn btn-default">
</form>
<?php endif; ?>

<form enctype="multipart/form-data" method="post" action="/?page=manage_shipping" class="form-inline">
    <input type="hidden" name="MAX_FILE_SIZE" value="3000000">
        load data from CSV:
        <div class="fileinput fileinput-new" data-provides="fileinput">
            <span class="btn btn-default btn-file">
                <span class="fileinput-new">Select file</span>
                <span class="fileinput-exists">Change</span>
                <input type="file" name="csv">
            </span>
            <span class="fileinput-filename"></span>
            <a href="#" class="close fileinput-exists" data-dismiss="fileinput" style="float: none">&times;</a>
        </div>
        <input type="submit" class="btn btn-default" value="load">
</form>