<?php if(!isset($_GET['p'])) $_GET['p'] = '1';?>
<div class="text-center">
    <ul class="pagination pagination-sm">
        <?php for ($page = 1; $page <= $this->get('pages')->pageCount; $page++): ?>
            <li <?php if($page == $_GET['p']): ?>class="active" <?php endif; ?>><a href="/?p=<?php echo $page; ?>"><?php echo $page; ?></a></li>
        <?php endfor; ?>
    </ul>
</div>
<div class="container">
    <?php foreach ($this->get('products') as $_product): ?>
    <div class="jumbotron">
            <div class="media">
                <a class="pull-left" href="?page=product_view&id=<?php echo $_product->getId(); ?>">
                    <img class="media-object" src="<?php echo $_product->getImage(); ?>">
                </a>
                <div class="media-body">
                    <a href="?page=product_view&id=<?php echo $_product->getId(); ?>" style="text-decoration: none">
                        <h2 class="media-heading"><?php echo $_product->getName(); ?></h2>
                    </a>
                    <span><p><?php echo "Sku: " . $_product->getSku();?></span>
                    <p>Price:
                        <span class="product_price <?php if($_product->isSpecialPriceApplied()): ?>old_price<?php endif; ?>">
                            <?php echo $_product->getPrice(); ?>
                        </span>
                        <?php if($_product->isSpecialPriceApplied()): ?>
                            <span class="product_price"><?php echo " " . $_product->getSpecialPrice(); ?></span>
                        <?php endif; ?>
                    </p>

                </div>
            </div>
    </div>
    <?php endforeach; ?>
</div>
<div class="text-center">
    <ul class="pagination pagination-sm">
        <?php for ($page = 1; $page <= $this->get('pages')->pageCount; $page++): ?>
            <li <?php if($page == $_GET['p']): ?>class="active" <?php endif; ?>><a href="/?p=<?php echo $page; ?>"><?php echo $page; ?></a></li>
        <?php endfor; ?>
    </ul>
</div>

