        <h1>Our Product List:</h1>
        <?php for ($page = 1; $page <= $pages->pageCount; $page++): ?>
            <a href="/?p=<?php echo $page; ?>"><?php echo $page; ?></a>
        <?php endfor; ?>
            <?php foreach ($products as $_product): ?>
                <a href="?page=product_view&id=<?php echo $_product->getId(); ?>">
                    <div class="item">
                        <img src="<?php echo $_product->getImage(); ?>">
                        <h2><?php echo $_product->getName(); ?></h2>
                        <span><p><?php echo "Sku: " . $_product->getSku();?></span>
                        <p>Price: <span class="product_price <?php if($_product->isSpecialPriceApplied()): ?>old_price<?php endif; ?>">
                            <?php echo $_product->getPrice(); ?>
                        </span>
                        <?php if($_product->isSpecialPriceApplied()): ?>
                            <span class="product_price"><?php echo " " . $_product->getSpecialPrice(); ?></span>
                        <?php endif; ?>
                    </div>
                </a>
                <form method="post" action="/?page=quote_add">
                    <input type="hidden" id="product_id" name="product_id" value=<?php echo $_product->getId(); ?>>
                    <input type="number" id="qty" name="qty">
                    <input type="submit" value="add to cart">
                </form>
            <?php endforeach; ?>

