<h1><a href="/">&larr;</a>Your Basket</h1>


<?php foreach ($products as $_product): ?>
    <a href="?page=product_view&id=<?php echo $_product->getId(); ?>">
        <div class="item">
            <img src="<?php echo $_product->getImage(); ?>">
            <h2><?php echo $_product->getName(); ?></h2>
            <span><p><?php echo "Sku: " . $_product->getSku();?></span>
            <p>Price: <span class="product_price <?php if($_product->isSpecialPriceApplied()): ?>old_price<?php endif; ?>">
                            <?php echo $_product->getPrice(); ?>
                        </span>
                <?php if($_product->isSpecialPriceApplied()): ?>
                    <span class="product_price"><?php echo " " . $_product->getSpecialPrice(); ?></span>
                <?php endif; ?>
            <p>Quantity: <?php echo $_product->getQty()?>            <form method="post" action="/?page=quote_delete">
                <input type="hidden" id="link_id" name="link_id" value="<?php echo $_product->getLink(); ?>">
                <input type="submit" value="delete">
            </form>

        </div>
    </a>
    <form method="post" action="/?page=quote_update">
        <input type="hidden" id="product_id" name="product_id" value="<?php echo $_product->getId(); ?>">
        <input type="hidden" id="link_id" name="link_id" value="<?php echo $_product->getLink(); ?>">
        Quantity: <input type="number" id="qty" name="qty" value="<?php echo $_product->getQty()?>">
        <input type="submit" value="update">
    </form>
<?php endforeach; ?>