<div class="container">
    <div class="jumbotron">
        <h2>Your Cart:</h2>
    </div>
</div>
<div class="container">
    <div class="jumbotron">
        <table class="table">
            <tr>
                <td>name</td>
                <td>image</td>
                <td>price</td>
                <td style="text-align: right">quantity</td>
                <td>
                <td>summary</td>
            </tr>
            <?php
                $products = $this->get('products');
                foreach ($products as $_product):
            ?>
                <tr>
                    <td><?php echo $_product->getName(); ?></td>
                    <td>
                        <a class="pull-left" href="?page=product_view&id=<?php echo $_product->getId(); ?>">
                            <img class="media-object img-small" src="<?php echo $_product->getImage(); ?>">
                        </a>
                    </td>
                    <td>
                        <?php
                        if($_product->isSpecialPriceApplied())
                            echo $_product->getSpecialPrice();
                        else
                            echo $_product->getPrice();
                        ?>
                    </td>
                    <td>
                        <form method="post" action="/?page=quote_update" class="navbar-form navbar-right form-inline">
                            <input type="hidden" id="product_id" name="product_id" value="<?php echo $_product->getId(); ?>">
                            <input type="hidden" id="link_id" name="link_id" value="<?php echo $_product->getLink(); ?>">
                            <input type="number" class="form-control" min="1" id="qty" name="qty" value="<?php echo $_product->getQty()?>" style="width: 60px">
                            <input type="submit" class="btn btn-default" value="update">
                        </form>
                    </td>
                    <td>
                        <form method="post" action="/?page=quote_delete" class="navbar-right">
                            <input type="hidden" id="link_id" name="link_id" value="<?php echo $_product->getLink(); ?>">
                            <input type="hidden" id="link_id" name="product_id" value="<?php echo $_product->getId(); ?>">
                            <input type="submit" class="btn btn-default" value="delete">
                        </form>
                    </td>
                    <td>
                        <?php echo (float) $_product->getPrice() * (float) $_product->getQty(); ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>



<div class="container">
    <div class="jumbotron">
        <form method="post" action="/?page=checkout_address" class="navbar-form">
            <input type="submit" class="btn btn-default" value="buy">
        </form>
    </div>
</div>